CONP-PCNO/conp-documentation

- datalad_dataset_addition_procedure.md
This adds Conda install instruction for datalad in case a user/developer prefers using that option to install datalad. 
Note: this was the only way I could install compatible version of git-annex with CONP datalad datasets so it might be good to provide an alternative option for the install.
> Added the Conda install instructions for datalad

- datalad_dataset_addition_procedure.md
This adds links to the different Install guidelines from the DataLad Handbook, including one for Mac OS X install.
> Add link to DataLad install guidelines

- datalad_dataset_addition_procedure.md
In this PR, the paragraph about git-annex and datalad versions was moved up as it implies to install on any system (linux or mac). The instruction for the conda install have been removed as they are identical to the ones mentioned in the DataLad Handbook and a link to the instructions is already present.
> Reorganize install section

- CONP_FAQ.md
Adds questions that could be raised when a user tries to download a LORIS-based dataset through DataLad.
Partly resolves https://github.com/CONP-PCNO/conp-portal/issues/218 since the issue is related to old version of DataLad automatically installed on Ubuntu...
> add some datalad related questions to the FAQ

- datalad_dataset_addition_procedure.md
This PR is a simple addition to the datalad_dataset_addition_procedure guide. It specifies the minimum annex version to be compatible with datasets
> Specified minimum annex version in documenation

- CONP_FAQ.md
This PR does the following:
- reorganization of the FAQ into 5 sections: 
- CONP, 
- Data Access & Download, 
- Data Upload, 
- Tools & Pipelines, 
- DataLad
- addition of tools and pipelines questions to the FAQ
This solves #16
> [FAQ] Reorganize FAQ and add tools and pipelines questions

- datalad_dataset_addition_procedure.md
This PR updates _datalad_dataset_addition_procedure.md_ to point at the miniconda procedure for installing DataLad at the DataLad Handbook, and remove other installation options for Linux systems which were not working well following the upgrade of git-annex to 8.2020.
> Updated datalad installation documentation

- CONP_FAQ.md
Added numbering to big sections of the FAQ so that it is clearer on the CONP portal display of the FAQ what are the different sections.
> Added numbering to big sections of FAQ

- CONP_FAQ.md
This was reported by one of the scholars that tested the portal. This fixes the DataLad link so that it redirects to the DataLad website instead of a "Not Found" page.
> Fix DataLad link in the FAQ

- CONP_DATS_fields.md
This PR updates the required field specification to cover `extraProperties->CONP_status` (as specified in https://github.com/CONP-PCNO/conp-dataset/pull/166) and, in the case of subdatasets, `extraProperties->parent_dataset_id` (as per https://github.com/CONP-PCNO/conp-dataset/pull/342).
> Updating required fields documentation.

- datalad_dataset_addition_procedure.md
This PR updates `datalad_dataset_addition_procedure.md` to emphasise that all files copied into the local copy of a new dataset repository must be explicitly added either to `git annex` or stored directly using `git add`.
> updating datalad dataset addition procedure for clarity

- .github/workflows/stale.yml
This PR propose to add a GitHub workflow to automatically label/close stale issues and PRs.
This was discussed in CONP-PCNO/conp-dataset#570.
> [ADD] GitHub workflow to auto label/close stale issues and PRs.

- Documentation_displayed_on_the_portal/Share_Dataset_Instruction_Page.md
- datalad_dataset_addition_procedure.md
This PR fixes a bug in the current documentation displayed on the portal and adds the proper link to the DATS editor in the documentation.
> Add proper link to the DATS GUI editor and quick fixes on the current documentation displayed on the portal

- Documentation_displayed_on_the_portal/CONP_portal_tutorial.md
This updates all the image URLs of the new CONP_portal_tutorial.md file so that they point to the GitHub raw content instead of a relative path.
> Update tutorial image URLs to raw github URLs so the portal can load them

- Developers-Notes/CONP_data_upload_admin.md
This update removes an overly restrictive permissions assignment from the documentation for setting up a user account; files in these accounts need to be globally accessible for download via datalad links.  In the absence of this command permissions are now inherited from `/data/proftpd/users`.
> Updating CONP ftp server admin documentation

- datalad_dataset_addition_procedure.md
Until we have final approval that the community server can be advertised in our share page, this PR updates the old share page with the newly written instructions present in [Documentation_displayed_on_the_portal/Share_Dataset_Instruction_Page.md](https://github.com/CONP-PCNO/conp-documentation/blob/master/Documentation_displayed_on_the_portal/Share_Dataset_Instruction_Page.md) with the exception of the community server section.
> Update documentation of the share page with latest documentation except for the community server option

- Documentation_displayed_on_the_portal/Share_Instruction_Page.md
As of version 0.15, the ```datalad publish``` command has been deprecated and is replaced by ```datalad push```.  There are some differences in available options but none that affect our usage. This PR updates the file sharing instructions in the CONP portal to reflect this change.
> Update file sharing instruction page for change to Datalad command.

- Developers-Notes/CONP_dataset_checks.md
- Documentation_displayed_on_the_portal/Share_Instruction_Page.md
This update corrects and clarifies a couple of points in the procedure for updating dataset links from the dataset providers' github repositories to forks stored in `conpdatasets`.
> Minor updates to CONP_dataset_checks.md

- Documentation_displayed_on_the_portal/Share_Instruction_Page.md
Recently something in the interaction of Datalad and Github has changed so that when a Github sibling is created using Datalad the default branch can be set to `git-annex`.  If this happens, adding that dataset as a submodule of `conp-dataset` according to our existing procedure gives a non-functional link.  Changing the default branch for a dataset on Github is straightforward, and this update adds a warning and instructions on how to do this to `Share_Instructions_Page.md`.
> Updating data share documentation to include note about changing default branch.

- Documentation_displayed_on_the_portal/Share_Instruction_Page.md
This PR adds a note to the `Share_Instruction_Page.md` file warning users to explicitly set the default branch of their github dataset to `main`, as github changing their default from `master`  to `main` caused the `datalad create-sibling-github` command to create repositories with the default branch set to `git-annex`, which was not functional.
> updating share instructions

- Documentation_displayed_on_the_portal/Share_Instruction_Page.md
This PR adds instructions to manually add `branch = main` to the `.gitmodules` file when adding a new dataset, in order to fix issues transferring data between servers arising from Github renaming the default branch from `master` to `main` (see https://github.com/github/renaming).
> Update documentation on share page for github default branch name change.

- Documentation_displayed_on_the_portal/CONP_FAQ.md
Change the quotes that are breaking the anchor links of the portal FAQ section.
> Fix FAQ navigation
