- CONP_main_data_documentation.htm
This PR modifies the style of two lists in _CONP_main_documentation.htm_ to add bullet points.
> modify list style in main documentation page

- CONP_FAQ.md
This PR adds a set of FAQs for the CONP portal; I have tried to be short and punchy and link to existing resources where possible. This is very much a first draft.
Two issues still outstanding here:
1) Should we explicitly mention in this context that DataLad is generating links to external resources rather than hosting them locally, and do we want to offer a local hosting option?
2) We should definitely have something about open science, restricted access and ORCIDs. I am not sure how best to phrase that to accurately convey what we are providing, so would particularly welcome input on this front.
> adding draft CONP FAQ file

- CONP_FAQ.md
- datalad_dataset_addition_procedure.md
Update documentation for possibility to upload datasets to CONP via OSF
> Upload datasets via OSF

- datalad_dataset_addition_procedure.md
Since the upload dataset documentation is now being displayed in the portal, the formatting has been reworked a bit so it makes it easier to read and navigate through visually.
> Updated the formatting of the upload dataset documentation

- CONP_DATS_fields.md
This PR updates CONP_DATS_fields.md to add `creators->name->roles->value("Principal Investigator")` as a recommended field where appropriate, as discussed in https://github.com/CONP-PCNO/conp-portal/issues/254.
> updating CONP_DATS_fields.md to document adding "Principal Investigator" to DATS model.

- UX-UI/ux_ui.md
Looks like there was already a link to Derek's sketch in this repo. This updates that link to the latest version of the sketch we will keep working on.
The link was provided by Derek and taken from the CONP dev agenda from last week
> Update the link to Derek's latest demo

- CONP_DATS_fields.md
This PR updates `CONP_DATS_fields.md` with instructions for creating a `DATS.json` file as suggested in https://github.com/CONP-PCNO/conp-documentation/issues/31.
> Updated CONP_DATS_fields.md with instructions for creating DATS model

- datalad_dataset_addition_experimental.md
This PR updates the globus initialization procedure done manually
This step is required when a dataset living in globus is added to CONP or updated (for example if its Globus ID changes)
> updates globus initialization procedure

- CONP_FAQ.md
The tutorial link was incorrect in the FAQ
> Correct link to the tutorial in the FAQ

- datalad_dataset_addition_experimental.md
- datalad_dataset_addition_procedure.md
This PR improves the current documentation on the steps to add a new dataset to CONP using the Globus Special Remote
> Improving Globus related documentation

- Publishing_Zenodo_through_Github.md
- academictorrent_notes.md
- json-to-json_ld/dataset_reference.txt
- json-to-json_ld/json_to_json-ld.pl
This PR adds four files transferred from the repository https://github.com/neurohub/neurohub_documentation, which more appropriately belong here.
> consolidating documentation from neurohub repository

- datalad_dataset_addition_procedure.md
This PR updates `datalad_dataset_addition_procedure.md` to replace a command which has been deprecated in datalad,
> modifying datalad dataset addition procedure document

- Developers-Notes/conp-dataset_creation_of_prezipped_archives_for_downloads.md
This adds an how to guide for the preparation of the prezipped dataset files that will be available for download.
> How to guide for preparation of the prezipped dataset files

- Documentation_displayed_on_the_portal/Share_Dataset_Instruction_Page.md
This integrates the feedback on the new Dataset addition procedure documentation that will eventually replace the content of the current Share page.
> Integrate feedback to the new Dataset addition procedure document

- Documentation_displayed_on_the_portal/Share_Dataset_Instruction_Page.md
This PR adds a small clarification to step 3 of the DataLad data update procedure based on recent interaction with a data provider.
> datalad data update procedure: text update for clarity

- Developers-Notes/CONP_dataset_checks.md
Documentation of procedures for addressing the issues raised in https://github.com/CONP-PCNO/conp-documentation/issues/86.
> New CONP dataset checks documentation.

- Developers-Notes/CONP_data_upload_admin.md
This PR updates `CONP_data_upload_admin.md` for the minor procedural modifications in https://github.com/CONP-PCNO/conp-dataset/pull/767.
> Update developer-facing documentation for crawling datasets on sftp.conp.ca

- Developers-Notes/CONP_VM_setups_and_maintenance/OSF_Zenodo_crawler_VM/crawler.md
This PR updates the OSF crawler documentation for the VM changes documented in https://redmine.cbrain.mcgill.ca/issues/21141#note-2.
> Updating server documentation for change in port number

- Documentation_displayed_on_the_portal/CONP_FAQ.md
These are changes that will support separating Download from Share instructions for the CONP Portal, with their correponding buttons on the frontend.
> Updates to CONP_FAQ.md

- Documentation_displayed_on_the_portal/Share_Instruction_Page.md
> Updates to Share_Instruction_Page.md
